services:
  postgres:
    image: postgres:latest
    container_name: ArtaferaDB
    environment:
      POSTGRES_USER: DBAdmin
      POSTGRES_PASSWORD: AVerySecurePassword
      POSTGRES_DB: ArtaferaDB
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: S3Admin
      MINIO_ROOT_PASSWORD: AVerySecurePassword
      MINIO_CONSOLE_ADDRESS: ":9001"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
volumes:
  postgres_data:
  minio_data:
