services:
  postgres:
    image: postgres:latest
    container_name: ArtaferaDB
    environment:
      POSTGRES_USER: DBAdmin
      POSTGRES_PASSWORD: AVerySecurePassword
      POSTGRES_DB: ArtaferaDB
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
 