name: Build and Push Backend Docker Image
on:
  push:
    branches:
      - main
      - Api-stuff
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/artafera-backend:latest
            ghcr.io/${{ github.repository_owner }}/artafera-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy via Dokploy API
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "User-Agent: GitHub-Hookshot/test" \
          -H "X-GitHub-Event: push" \
          -d '{
            "ref": "refs/heads/main",
            "repository": {
              "full_name": "ienjir/artafera-backend"
            }
          }'
